<?php
/**
 * @var array $hotels
 */
?>
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- BOOTSTRAP LINK -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Hoteles Mallorca</title>
    <style>
        img {
            height: 250px;
        }
    </style>
</head>
<body>

    <!-- HEADER -->
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow p-4 mb-3">
            <div class="container">
                <a href="MainController.php" class="navbar-brand">Inicio</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <?php if (isset($_SESSION["userId"])) { ?>
                        <a href="LogoutController.php" class="nav-link text-dark">Cerrar sesión</a>
                    <?php } else { ?>
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a href="SigninController.php" class="nav-link text-dark">Iniciar sesión</a>
                            </li>
                            <li class="nav-item">
                                <a href="SignupController.php" class="nav-link text-dark">Registrarse</a>
                            </li>
                        </ul>
                    <?php } ?>
                </div>
            </div>
        </nav>
    </header>

    <!-- CONTENT -->
    <section>

        <h1 class="display-4 m-4 text-center">Hoteles Mallorca</h1>

        <!-- HOTELS CARDS -->
        <div class="row row-cols-1 row-cols-md-2 p-5 g-4 text-center">
            <?php
            foreach ($hotels as $hotel) { ?>
                <div class="col-lg-4 my-3">
                    <div class="card h-100">
                        <img src="<?php echo $hotel->getImages()[0]->getUrl() ?>" class="card-img-top" alt="image">
                        <div class="card-header">
                            <h4 class="card-title"><?php echo $hotel->getName() ?></h4>
                            <h6><?php echo $hotel->getTown()->getName() ?></h6>
                            <small><?php echo $hotel->getStreet() ?></small>
                        </div>
                        <div class="card-body">
                            <p class="card-text"><?php echo $hotel->getDescription() ?></p>
                        </div>
                        <hr />
                        <div class="col-lg-12 text-center">
                            <a href="SingleController.php?id=<?php echo $hotel->getId() ?>" class="btn btn-dark col-lg-4 mb-3">Reservar</a>
                        </div>
                    </div>
                </div>
            <?php } ?>
        </div>

    </section>

    <!-- FOOTER -->
    <footer class="border-top footer navbar-fixed-bottom text-muted p-4">
        <div class="container">
            &copy; 2022 - Hoteles Mallorca
        </div>
    </footer>

    <!-- BOOTSTRAP LINK -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

</body>
</html>
