<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- BOOTSTRAP LINK -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Iniciar sesión</title>
</head>
<body>

    <!-- HEADER -->
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow p-4">
            <div class="container">
                <a href="MainController.php" class="navbar-brand">Inicio</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <?php if (isset($_SESSION["userId"])) { ?>
                        <a href="LogoutController.php" class="nav-link text-dark">Cerrar sesión</a>
                    <?php } else { ?>
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a href="SigninController.php" class="nav-link text-dark">Iniciar sesión</a>
                            </li>
                            <li class="nav-item">
                                <a href="SignupController.php" class="nav-link text-dark">Registrarse</a>
                            </li>
                        </ul>
                    <?php } ?>
                </div>
            </div>
        </nav>
    </header>

    <!-- CONTENT -->
    <section class="d-flex justify-content-center">

        <!-- SIGN IN FORM -->
        <form method="post" class="col-lg-3 h-50 d-flex flex-wrap border rounded mt-5 p-4">

            <h5 class="mb-4 col-12 text-center" style="letter-spacing: 1px;">Iniciar sesión</h5>

            <!-- EMAIL -->
            <div class="form-outline col-12 mb-1">
                <input type="email" id="inputEmail" name="email" class="form-control form-control-sm mb-1" required />
                <label class="form-label" for="inputEmail">Correo electrónico</label>
            </div>

            <!-- PASSWORD -->
            <div class="form-outline col-12 mb-1">
                <input type="password" id="inputPassword" name="password" class="form-control form-control-sm mb-1" required />
                <label class="form-label" for="inputPassword">Contraseña</label>
            </div>

            <!-- SUBMIT -->
            <button class="btn btn-dark col-lg-12 my-2" type="submit">Iniciar</button>

        </form>

    </section>

    <!-- FOOTER -->
    <footer class="border-top footer fixed-bottom text-muted p-4">
        <div class="container">
            &copy; 2022 - Hoteles Mallorca
        </div>
    </footer>

    <!-- BOOTSTRAP LINK -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>
